# Generated by Django 5.0.7 on 2024-07-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vflabs_home', '0002_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
