# Generated by Django 3.2.12 on 2024-08-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflabs_home', '0003_remove_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
