# Generated by Django 3.2.12 on 2024-08-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vflabs_home', '0004_auto_20240804_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
