# Generated by Django 3.2.12 on 2024-08-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vflabs_home', '0005_investment_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='name',
            new_name='full_name',
        ),
    ]
